version: '3'

services:
  app:
    container_name: newsstand-backend
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - ENV=${ENV}
      #- PORT=${PORT}
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - DOMAIN=${DOMAIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      custom_network:
        ipv4_address: 172.16.238.10

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24