version: '3.0'

services:
  app:
    container_name: newsstand-backend
    build: .
    env_file: 
      - ../../environment/.env
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - /app/node_modules
