version: '3'

services:
  app:
    container_name: newsstand-backend
    build: .
    ports:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      custom_network:
        ipv4_address: 172.16.238.10

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24